import ConvexNivat.ReductionDefinitions
import ConvexNivat.CorePeriods

namespace ConvexNivat

/-- Lemma 8.13 with the concrete period generated by characteristic p. -/
theorem finiteField_difference_period (p : ℕ) (hp : p.Prime)
    (G : Configuration (ZMod p)) (d : Lattice) (M : ℕ) (hM : 0 < M)
    (h : HasPeriod (fun z => G (z + d) - G z) ((M : ℤ) • d)) :
    HasPeriod G (((p * M : ℕ) : ℤ) • d) := by
  -- Telescoping the short differences makes the long difference periodic.
  have hlong : ∀ n : ℕ,
      HasPeriod (fun z => G (z + (n : ℤ) • d) - G z) ((M : ℤ) • d) := by
    intro n
    induction n with
    | zero => intro z; simp
    | succ n ih =>
      intro z
      have hn := ih z
      have hd := h (z + (n : ℤ) • d)
      simp only [Nat.cast_add, Nat.cast_one, add_smul, one_smul]
      simp only [add_assoc, add_comm, add_left_comm] at hn hd ⊢
      linear_combination hn + hd
  -- Repetition of the long step adds the same field element each time.
  have hrepeat : ∀ n : ℕ, ∀ z : Lattice,
      G (z + (n : ℤ) • ((M : ℤ) • d)) - G z =
        n • (G (z + (M : ℤ) • d) - G z) := by
    intro n
    induction n with
    | zero => intro z; simp
    | succ n ih =>
      intro z
      have hn := ih z
      have hd := hasPeriod_zsmul _ _ (hlong M) (n : ℤ) z
      simp only [Nat.cast_add, Nat.cast_one, add_smul, one_smul]
      simp only [add_comm, add_left_comm] at hn hd ⊢
      linear_combination hn + hd
  intro z
  have hz := hrepeat p z
  rw [ZModModule.char_nsmul_eq_zero] at hz
  simpa only [smul_smul, Nat.cast_mul, sub_eq_zero] using hz

/-- Lemma 8.13, without an unnecessary minimality assumption. -/
theorem lemma8_13 (p : ℕ) (hp : p.Prime) (G : Configuration (ZMod p))
    (h d : Lattice) (hh : h ≠ 0) (hG : HasPeriod G h)
    (hd : Nonparallel h d)
    (hdiff : DoublyPeriodic (fun z => G (z + d) - G z)) :
    DoublyPeriodic G := by
  obtain ⟨M, hM, hgrid⟩ :=
    (doublyPeriodic_iff_grid (fun z => G (z + d) - G z)).mp hdiff
  refine ⟨h, (((p * M : ℕ) : ℤ) • d), ?_, hG,
    finiteField_difference_period p hp G d M hM (hgrid d)⟩
  have hscale : ((p * M : ℕ) : ℤ) ≠ 0 := by
    exact_mod_cast Nat.ne_of_gt (Nat.mul_pos hp.pos hM)
  have hdet : det h (((p * M : ℕ) : ℤ) • d) =
      ((p * M : ℕ) : ℤ) * det h d := by
    simp [det]
    ring
  rw [Nonparallel, hdet]
  exact mul_ne_zero hscale hd

end ConvexNivat
