import ConvexNivat.Geometry.Triangulation.Definitions
import Mathlib.Analysis.Normed.Affine.AddTorsorBases
import Mathlib.Tactic

namespace ConvexNivat.PolygonTriangulation

open scoped BigOperators

/-- PT16: erasing precisely a redundant lattice generator leaves the real hull. -/
theorem erase_redundant_hull_generator (S : Finset Lattice) (q : Lattice)
    (hq : q ∈ S) :
    (embed q ∈ windowHull (S.erase q) ↔ windowHull (S.erase q) = windowHull S) ∧
    windowHull (S.erase q) ⊆ windowHull S := by
  classical
  have hsub : windowHull (S.erase q) ⊆ windowHull S :=
    convexHull_mono (Set.image_mono (by exact Finset.erase_subset q S))
  refine ⟨⟨?_, ?_⟩, hsub⟩
  · intro he
    refine Set.Subset.antisymm hsub (convexHull_min ?_ (convex_convexHull ℝ _))
    rintro _ ⟨z, hz, rfl⟩
    by_cases h : z = q
    · simpa [h] using he
    · exact subset_convexHull ℝ _ ⟨z, Finset.mem_erase.mpr ⟨h, hz⟩, rfl⟩
  · intro he
    rw [he]
    exact subset_convexHull ℝ _ ⟨q, hq, rfl⟩

/-- PT17: the same hull is generated by an actual minimum-cardinality subset. -/
theorem minimal_irredundant_lattice_generators (S : Finset Lattice)
    (hS : (interior (windowHull S)).Nonempty) :
    ∃ Q : Finset Lattice, Q ⊆ S ∧ windowHull Q = windowHull S ∧
      Q.Nonempty ∧ Irredundant Q ∧
      ∀ U : Finset Lattice, U ⊆ S → windowHull U = windowHull S → Q.card ≤ U.card := by
  classical
  let candidates := S.powerset.filter (fun Q => windowHull Q = windowHull S)
  have hc : candidates.Nonempty := ⟨S, by simp [candidates]⟩
  obtain ⟨Q, hQ, hmin⟩ := candidates.exists_min_image Finset.card hc
  have hQS : Q ⊆ S := Finset.mem_powerset.mp (Finset.mem_filter.mp hQ).1
  have hHull : windowHull Q = windowHull S := (Finset.mem_filter.mp hQ).2
  have hm : ∀ U : Finset Lattice, U ⊆ S → windowHull U = windowHull S →
      Q.card ≤ U.card := by
    intro U hUS hU
    exact hmin U (Finset.mem_filter.mpr ⟨Finset.mem_powerset.mpr hUS, hU⟩)
  refine ⟨Q, hQS, hHull, ?_, ?_, hm⟩
  · by_contra hn
    have hzero : Q = ∅ := Finset.not_nonempty_iff_eq_empty.mp hn
    have : windowHull S = ∅ := by
      rw [← hHull, hzero]
      simp [windowHull]
    simp [this] at hS
  · intro q hq he
    have hErase := (erase_redundant_hull_generator Q q hq).1.mp he
    have hle := hm (Q.erase q) ((Finset.erase_subset q Q).trans hQS) (hErase.trans hHull)
    have hcard := Finset.card_erase_lt_of_mem hq
    omega

/-- PT18: a real hull generated by at most two lattice points has no interior. -/
theorem hull_of_at_most_two_has_empty_interior :
    (∀ S : Finset Lattice, S.card ≤ 2 → interior (windowHull S) = ∅) ∧
    (∀ S : Finset Lattice, (interior (windowHull S)).Nonempty → 3 ≤ S.card) := by
  have hempty : ∀ S : Finset Lattice, S.card ≤ 2 → interior (windowHull S) = ∅ := by
    intro S hcard
    apply Set.not_nonempty_iff_eq_empty.mp
    intro hi
    have htop := (convex_convexHull ℝ (embed '' (S : Set Lattice))).interior_nonempty_iff_affineSpan_eq_top.mp hi
    rw [affineSpan_convexHull] at htop
    have hle : (S : Set Lattice).encard ≤ Module.finrank ℝ RealPlane := by
      simpa [Module.finrank_prod] using (show (S.card : ℕ∞) ≤ (2 : ℕ∞) by exact_mod_cast hcard)
    exact affineSpan_image_ne_top_of_encard_le_finrank ℝ S.finite_toSet hle embed htop
  refine ⟨hempty, ?_⟩
  intro S hi
  by_contra hc
  have he := hempty S (by omega)
  simp [he] at hi

private theorem strict_support_convex (N : ℕ) (p : RealPlane) :
    Convex ℝ {x : RealPlane | 0 ≤ ell N (x - p) ∧ (ell N (x - p) = 0 → x = p)} := by
  intro x hx y hy a b ha hb hab
  have hlin : ell N (a • x + b • y - p) =
      a * ell N (x - p) + b * ell N (y - p) := by
    dsimp [ell]
    nlinarith [congrArg (fun t : ℝ => t * (N : ℝ) * p.1) hab,
      congrArg (fun t : ℝ => t * p.2) hab]
  have hx0 := hx.1
  have hy0 := hy.1
  have hax := mul_nonneg ha hx0
  have hby := mul_nonneg hb hy0
  refine ⟨by rw [hlin]; exact add_nonneg hax hby, ?_⟩
  intro hz
  have hzero : a * ell N (x - p) + b * ell N (y - p) = 0 := by
    rw [← hlin]; exact hz
  have hax0 : a * ell N (x - p) = 0 := by linarith
  have hby0 : b * ell N (y - p) = 0 := by linarith
  have hxa : a • (x - p) = 0 := by
    rcases mul_eq_zero.mp hax0 with ha0 | hxell
    · simp [ha0]
    · simp [hx.2 hxell]
  have hyb : b • (y - p) = 0 := by
    rcases mul_eq_zero.mp hby0 with hb0 | hyell
    · simp [hb0]
    · simp [hy.2 hyell]
  calc
    a • x + b • y = a • (x - p) + b • (y - p) + (a + b) • p := by module
    _ = p := by rw [hxa, hyb, hab]; simp

/-- PT19: construct an exposed lattice anchor; all outputs share the same p,N. -/
theorem strict_integer_exposed_anchor (Q : Finset Lattice) (hQ : Q.Nonempty)
    (hirr : Irredundant Q) (hdim : (interior (windowHull Q)).Nonempty) :
    ∃ p : Lattice, ∃ N : ℕ, Anchor Q p N ∧
      (∀ x y : RealPlane, realDet x y =
        ell N x * kappa y - kappa x * ell N y) ∧
      (∀ x ∈ windowHull Q, 0 ≤ ell N (x - embed p) ∧
        (ell N (x - embed p) = 0 ↔ x = embed p)) := by
  classical
  obtain ⟨r, hr, hfirst⟩ := Q.exists_min_image Prod.fst hQ
  let F := Q.filter (fun q => q.1 = r.1)
  have hF : F.Nonempty := ⟨r, by simp [F, hr]⟩
  obtain ⟨p, hpF, hsecond⟩ := F.exists_min_image Prod.snd hF
  obtain ⟨hp, hpr⟩ := Finset.mem_filter.mp hpF
  let N := 1 + ∑ q ∈ Q, (q.2 - p.2).natAbs
  have hanchor : Anchor Q p N := by
    refine ⟨hp, ?_⟩
    intro q hq
    obtain ⟨hqp, hqQ⟩ := Finset.mem_erase.mp hq
    have hle : p.1 ≤ q.1 := by rw [hpr]; exact hfirst q hqQ
    have hpos : 0 < (N : ℤ) * (q.1 - p.1) + (q.2 - p.2) := by
      by_cases heq : q.1 = p.1
      · have hqF : q ∈ F := Finset.mem_filter.mpr ⟨hqQ, heq.trans hpr⟩
        have hle2 := hsecond q hqF
        have hne2 : q.2 ≠ p.2 := by
          intro h
          exact hqp (Prod.ext heq h)
        have : p.2 < q.2 := by omega
        simp only [heq, sub_self, mul_zero, zero_add]
        omega
      · have hgap : 1 ≤ q.1 - p.1 := by omega
        have hsum : (q.2 - p.2).natAbs ≤ ∑ q ∈ Q, (q.2 - p.2).natAbs :=
          Finset.single_le_sum (f := fun q : Lattice => (q.2 - p.2).natAbs)
            (fun _ _ => Nat.zero_le _) hqQ
        have hN : (q.2 - p.2).natAbs < N := by dsimp [N]; omega
        have hN' : ((q.2 - p.2).natAbs : ℤ) < (N : ℤ) := by exact_mod_cast hN
        have hneg := Int.le_natAbs (a := -(q.2 - p.2))
        simp only [Int.natAbs_neg] at hneg
        have hN0 : 0 ≤ (N : ℤ) := Int.natCast_nonneg N
        have hmul : (N : ℤ) ≤ (N : ℤ) * (q.1 - p.1) := by nlinarith
        omega
    dsimp [ell, embed]
    exact_mod_cast hpos
  refine ⟨p, N, hanchor, ?_, ?_⟩
  · intro x y
    dsimp [realDet, ell, kappa]
    ring
  · have hs : embed '' (Q : Set Lattice) ⊆
        {x : RealPlane | 0 ≤ ell N (x - embed p) ∧
          (ell N (x - embed p) = 0 → x = embed p)} := by
      rintro _ ⟨q, hq, rfl⟩
      by_cases heq : q = p
      · simp [heq, ell]
      · have hpos := hanchor.2 q (Finset.mem_erase.mpr ⟨heq, hq⟩)
        have hsub : embed (q - p) = embed q - embed p := by ext <;> simp [embed]
        rw [hsub] at hpos
        exact ⟨hpos.le, fun h => False.elim (ne_of_gt hpos h)⟩
    intro x hx
    obtain ⟨hnonneg, heq⟩ := convexHull_min hs (strict_support_convex N (embed p)) hx
    refine ⟨hnonneg, heq, ?_⟩
    intro h
    simp [h, ell]

end ConvexNivat.PolygonTriangulation
